### ISSUE TITLE
Display library patch version on library page

### ISSUE THREAD

**Issue by sed-i** [canonical/charmhub.io#1386]
To check the version of the library one must display source code and scroll down to `LIBPATCH`.
It would be handy if the lib page showed the full version at the top, e.g. `Library version 0.22`.

![Screenshot from 2022-08-10 14-06-46](https://user-images.githubusercontent.com/82407168/183985807-f79e1976-2b27-486c-9a98-de185376c247.png)

**Comment by rahulsinghcanonical** [comment]
The reason the library version is 0 is because in the code it is printing the api_version (of the API call which is 0). This is not the library version.

If you look at the libraries_layout.html file:
```
<li class="p-inline-list__item">
                <i class="p-icon--revision">Revision</i> Library version {{ library['api'] }}
```
which is coming from webapp/store/views.py file
             `library = publisher_api.get_charm_library(entity_name, library_id)`

The get_charm_library is defined in
https://github.com/canonical/canonicalwebteam.store-api/blob/main/canonicalwebteam/store_api/stores/charmstore.py
