### ISSUE TITLE
Unable to change charm homepage

### ISSUE THREAD

**Issue by mthaddon** [canonical/charmhub.io#1400]
I just tried to change the charm homepage on https://charmhub.io/nginx-ingress-integrator/listing from `https://launchpad.net/charm-k8s-ingress` to `https://github.com/canonical/nginx-ingress-integrator-operator`. When I hit the "save" button it tells me "changes successfully applied" but the homepage field still shows the launchpad location rather than github location.

**Comment by jkfran** [comment]
This issue is coming from the API. Here is what's going on:

**Charm without website previously specified:**
It works fine. You can log in as a publisher and set up an URL. Behind the scenes we are using this endpoint: https://api.charmhub.io/docs/default.html#update_package_metadata (`PATCH` HTTP method) with the following payload:
```
    data = {
        "contact": "",
        "summary": "Summary",
        "title": "New title or previous one",
        "website": https://new.site,
    }
```

**Charm with website previously specified:**
Here is the issue and the misbehaviour from the API, we use the same endpoint, the same HTTP method and the same payload (obviously changing the website value). This is the API response:
```
{
  "name": "landscape-keystone", 
  "private": false, 
  [...]
  "website": "https://new.site"
}
```

The response report back the new URL, however, the data is not persistent, and the info endpoint in the consumer API (`https://api.charmhub.io/v2/charms/info/CHARM_NAME?fields=result.website`) will return the old URL.

@Roadmaster could you investigate on your side? Thank you.

**Comment by tartley** [comment]
Snap store team have identified the problem and a possible fix. I'll work on something the remainder of today, shooting for a release on Monday.

**Comment by jkfran** [comment]
Hello @tartley, thank you for looking into it. Any updates?

**Comment by tartley** [comment]
Does this work? I made a diagram while diagnosing what was going wrong, and at that point it was easy to cut-and-paste the same diagram to illustrate the fix.
![sequence](https://user-images.githubusercontent.com/137979/190412295-a7879c31-471a-4832-a2bd-5680e34af58a.svg)
The change has taken longer than I thought because 'website' is not the only affected field, but it's getting there now. I'll post here when it lands in staging & prod.

**Comment by jkfran** [comment]
@tartley Thank you for keeping us posted.

**Comment by mthaddon** [comment]
@tartley hi there, things still progressing on this one? Wondering if you have an estimated timeline, just so I know when to check in again?

**Comment by tartley** [comment]
Hi. Sorry this has taken ages. I keep converging on a fix and then realizing I've broken everything else. Dumb mutable structures being used in different places in the code. I have a handle on it now, [first MP](https://code.launchpad.net/~tartley/publishergw/+git/publishergw/+merge/430762) submitted, more to follow very soon.

**Comment by Lukewh** [comment]
@tartley any update on the subsequent MP's?

**Comment by tartley** [comment]
QA of my MPs is finally done. Awaiting a slot to deploy to prod, which only happens during "Americas" team office hours, so probably will go out at around noon tomorrow UTC.

**Comment by tartley** [comment]
@Lukewh This is deployed to prod now and seems to be working. Apologies for the delays.

**Comment by mthaddon** [comment]
Thanks, I can confirm it's working, will close out this issue.
