### ISSUE TITLE
charm tracks/channels information is super verbose and inaccurate?

### ISSUE THREAD

**Issue by javacruft** [canonical/charmhub.io#1491]
I'm not sure whether this is a recent change but we have a lot of charms in the OpenStack charm set with numerous tracks, differing support for Ubuntu releases and supporting multiple architectures.

Example:  https://charmhub.io/keystone?channel=zed/stable

The 'platform' part of the page is confusing and not accurate - juju info returns what we think is the correct view of the world:

```
$ juju info --channel zed keystone
name: keystone
publisher: OpenStack Charmers
summary: OpenStack identity service
description: |
  Keystone is an OpenStack project that provides Identity, Token, Catalog and
  Policy services for use specifically by projects in the OpenStack family. It
  implements OpenStack's Identity API.
store-url: https://charmhub.io/keystone
charm-id: KR2vfZJptPGPnOBSMGU0L516cGTTwNam
supports: jammy, kinetic
[snip]
channels: |
  zed/stable:     591  2023-01-23  (591)  788kB
  zed/candidate:  ↑
  zed/beta:       ↑
  zed/edge:       ↑
```

Highlighted by an end user who was trying to work out which charm track/revision still supported focal.

**Comment by lathiat** [comment]
+1 on this from me, came to report the same thing.

I am fairly sure this changed at some point in the last couple of months, because, now each of the openstack charm pages have this very long single column list of supported releases over and over and I am reasonably sure I never saw that previously. Having said that the name and number of channels published has been changing and it's possible it had the same but in a wider non-single-column view and thus I am remembering wrong because of that.

**Comment by nobuto-m** [comment]
Just for the record.

![image](https://user-images.githubusercontent.com/4356209/219596496-bb2ecf2a-1258-4d51-a6d8-c89de4f29c4e.png)

Older Ubuntu releases such as 12.04 LTS, 14.04 LTS, 16.04 LTS and on are not supported by zed/stable but somehow shown as "runs on".

**Comment by steverydz** [comment]
Thanks for the bug report. This should be fixed now.
