### ISSUE TITLE
Charm subtitle: display maintainers rather than owner?

### ISSUE THREAD

**Issue by sed-i** [canonical/charmhub.io#1522]
Currently charmhub displays the owner of the charm in the subtitle:
![image](https://user-images.githubusercontent.com/82407168/221011651-d841226d-f857-456d-8b26-e5a4982f793c.png)

Shouldn't it be a list of maintainers instead, [taken from metadata](https://github.com/canonical/grafana-k8s-operator/blob/f86a533636e6ab99ed7d2ac91093adb866417105/metadata.yaml#L13)?
![image](https://user-images.githubusercontent.com/82407168/221011747-5f409f5a-949e-4cdc-bf52-37b9a1ddbf81.png)

Perhaps the following order of precedence makes sense?
1. `maintainers` section in metadata (if present); otherwise
2. `CODEOWNERS` file<sup>[[gh](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), [gl](https://docs.gitlab.com/ee/user/project/code_owners.html#code-owners-file)]</sup> (if present); otherwise
3. Charm owner (fallback)

cc: @tmihoc

**Comment by Lukewh** [comment]
This information would need to be exposed in the store-api, I've created an issue here, for tracking https://bugs.launchpad.net/snapstore-server/+bug/2009183

Regarding changing the header, the publisher would remain the same for consistency within teams, however “maintainer” would be an additional field on the page lower down. This is partly about consistency (maintainers change and can be a long list that wouldn't fit neatly in the header), and partly about providing a stronger sense of trust for users.

**Comment by Roadmaster** [comment]
> Shouldn't it be a list of maintainers instead, [taken from metadata](https://github.com/canonical/grafana-k8s-operator/blob/f86a533636e6ab99ed7d2ac91093adb866417105/metadata.yaml#L13)?

I don't think it should be that *instead* - it should always display the owner/publisher and display the maintainers if they are explicitly indicated in the metadata file.

I would not display data from CODEOWNERS directly; I don't want to bake knowledge about code provider-specific files into the store. Instead, I would advocate for charmcraft to extract data from CODEOWNERS and format/place it in the metadata file or manifest (probably manifest, since we don't modify the metadata file; the manifest is generated by charmcraft with build-time information and is somewhat analogous to snap.yaml; and remember that for snaps we do something similar where snapcraft extracts metadata from e.g. appstream xml files and puts that in the  snap.yaml file).

Right now, the metadata file is exposed verbatim through the API so if there is maintainers information there, it could potentially already be displayed on the web.

curl -s 'https://api.charmhub.io/v2/charms/info/grafana-k8s?channel=edge&fields=default-release.revision.metadata-yaml' | jq '."default-release".revision."metadata-yaml"'

**Comment by tmihoc** [comment]
@Lukewh @Roadmaster any progress with this?

**Comment by Lukewh** [comment]
Slipped off the radar, I'll add a ticket to look into it some more next pulse :)
https://warthogs.atlassian.net/browse/WD-4630
