### ISSUE TITLE
Charmhub Integrations tab minor issues: wrong help/channel and missing charms

### ISSUE THREAD

**Issue by taurus-forever** [canonical/charmhub.io#1598]
Hi,

Several minor issues for the tab "Integrations" on charmhub.io:

1. The [bubble help](https://charmhub.io/s3-integrator/integrations) says "Relation | Interface". IMHO, the correct is "Endpoint | Interface".
2. Strange channel  `8.0/stable/8.0` or `14/stable/14` shown for charms where default track is not latest (e.g. mysql, postgresql). Example: https://charmhub.io/s3-integrator/integrations NOTE: the syntax `14/stable/14` is reserved for `<track>/<risk>/<branch>` (see "Anatomy of a channel" [here](https://ubuntu.com/blog/controlling-snap-releases-with-channels-tracks-and-branches-part-1)). 
4. For some reason here https://charmhub.io/mysql/integrations "No charms found that provide or consume s3", hovewer here https://charmhub.io/s3-integrator/integrations you can see four "Charms that consume s3". Can it be related to non-default/closed track `latest`?

Thank you for the answers and fixes!

**Comment by Lukewh** [comment]
Thanks for the report, Alex!

1. The terminology was agreed some time ago, and I think it will probably need to be part of a larger discussion. Perhaps something @massigori might want to get involved with down the line. I'd like to avoid changing things without full agreement :slightly_smiling_face: .
2. This is indeed a bug, that I'm fixing now :+1:
3. I think this is also a bug – I believe it is indeed the case that there are consumers of s3, but nothing in “latest” that provide. The issue is that the wording of the error is misleading, it should say “No charms found that provide s3” in this case. I'll also fix this :slightly_smiling_face:

**Comment by taurus-forever** [comment]
Dear @Lukewh , thank you for your comments and fixes!
I confirm the fix for issue #2 and wording improvements for #3. Tnx!

re: 3) .. but nothing in “latest” that provide 's3'.

There is a charm [s3-integrator](https://charmhub.io/s3-integrator/integrations) which is available in the `latest/stable` and it provides `s3`.
Q: why is it still missing in https://charmhub.io/mysql/integrations (section "s3")?

re: 1) "Relation | Interface" VS "Endpoint | Interface".  CC: @simskij @jnsgruk

**Comment by Lukewh** [comment]
@taurus-forever it looks like “s3-integrator” is set as “unlisted”. This means that the charm is visible if you visit the URL directly, but it is not included in search results (which is how we populate the available integrations) :).

**Comment by taurus-forever** [comment]
Dear @Lukewh , thank you! Unlisted charm status is the answer.

I have [requested](https://github.com/canonical/charmhub.io/issues/1620) charmhub.io improvements to visualize charm status as currently this configuration option is invisible for charm authors and produces a lot of confusion.

Thank you!
